#!/usr/bin/env node
/**
 * Publish the static export in `out/` to the `gh-pages` branch, then hand it
 * to GitHub Pages via the `pages.yml` Actions workflow.
 *
 * The site is built LOCALLY on purpose: `public/data/*.json` and
 * `public/collections/` are generated by `npm run data:*` using the Helius /
 * OpenSea keys in `.env.local`. Building here means those keys never need to
 * exist on GitHub — no Actions secrets, no CI credentials. The workflow only
 * ever checks out the already-built `gh-pages` branch; it does not build.
 *
 * `gh-pages` is force-pushed as a single orphan commit every time, so the
 * generated data never accumulates across deploys.
 *
 * Publishing via Actions (added 2026-08-06) rather than relying on GitHub's
 * classic branch-based Pages build replaced a real failure mode: that legacy
 * Jekyll pipeline has a hard 10-minute ceiling, and it started intermittently
 * blowing through it for this repo — a plain static export going from a
 * historical ~25s build to 300-500s+, with several outright timeouts.
 * Nothing here got slower; GitHub's pipeline did. `.github/workflows/
 * pages.yml` bypasses that pipeline entirely. Requires the repo's Pages
 * source to be set to "GitHub Actions" (not the classic branch source) — see
 * the workflow file for the one-time `gh api` command that sets it.
 *
 *   npm run deploy      # build + publish
 */
import { execFileSync } from "node:child_process";
import { existsSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const out = resolve(root, "out");

const run = (cmd, args, cwd) =>
  execFileSync(cmd, args, { cwd, stdio: "inherit" });

const capture = (cmd, args, cwd) =>
  execFileSync(cmd, args, { cwd, encoding: "utf8" }).trim();

const tryCapture = (cmd, args, cwd) => {
  try {
    return capture(cmd, args, cwd);
  } catch {
    return null;
  }
};

// --- preflight -------------------------------------------------------------
if (!existsSync(out)) {
  console.error("out/ not found — run `npm run build` first.");
  process.exit(1);
}
for (const f of ["index.html", "CNAME"]) {
  if (!existsSync(resolve(out, f))) {
    console.error(`out/${f} is missing — refusing to deploy an incomplete build.`);
    process.exit(1);
  }
}

// Never publish a build that carries the offline pipeline or a credential.
const forbidden = ["scripts", "masks", ".env", ".env.local"];
for (const f of forbidden) {
  if (existsSync(resolve(out, f))) {
    console.error(`out/${f} exists — refusing to deploy. Investigate before retrying.`);
    process.exit(1);
  }
}

// GitHub Pages runs Jekyll, which silently drops every path starting with "_".
// Without this file the entire /_next/ bundle 404s and the site renders as
// unstyled HTML. Written here as well as public/ so a deploy can never lose it.
writeFileSync(resolve(out, ".nojekyll"), "");

const remote = capture("git", ["remote", "get-url", "origin"], root);
console.log(`Deploying out/ -> gh-pages on ${remote}\n`);

// --- publish ---------------------------------------------------------------
// A throwaway repo inside out/, force-pushed. Keeps gh-pages at one commit.
rmSync(resolve(out, ".git"), { recursive: true, force: true });
run("git", ["init", "-q", "-b", "gh-pages"], out);
run("git", ["add", "-A"], out);
run("git", ["commit", "-q", "-m", `Deploy ${new Date().toISOString()}`], out);
run("git", ["push", "-q", "--force", remote, "gh-pages:gh-pages"], out);
rmSync(resolve(out, ".git"), { recursive: true, force: true });

console.log("Pushed gh-pages. Triggering the Pages publish workflow...\n");

// --- trigger the Actions publish -------------------------------------------
// The gh-pages push above is data only now (Pages source = "GitHub Actions",
// not the branch) — nothing serves it until this workflow runs. Fail loudly
// if it can't be triggered rather than reporting success on a branch push
// that will otherwise sit there unpublished with no indication anything is
// wrong, which is exactly the failure mode this replaced.
const ghVersion = tryCapture("gh", ["--version"], root);
if (!ghVersion) {
  console.error(
    "gh CLI not found — gh-pages was updated but NOT published.\n" +
      "Install/authenticate the GitHub CLI, or trigger it manually:\n" +
      "  gh workflow run pages.yml --ref main\n" +
      "or from the repo's Actions tab: \"Publish to Pages\" -> Run workflow."
  );
  process.exit(1);
}

const dispatched = tryCapture(
  "gh",
  ["workflow", "run", "pages.yml", "--ref", "main"],
  root
);
if (dispatched === null) {
  console.error(
    "Could not trigger the publish workflow (gh-pages was updated).\n" +
      "Trigger it manually:\n" +
      "  gh workflow run pages.yml --ref main\n" +
      "or from the repo's Actions tab: \"Publish to Pages\" -> Run workflow."
  );
  process.exit(1);
}

console.log(
  "Triggered. Watch it with:\n" +
    "  gh run watch $(gh run list --workflow=pages.yml -L1 --json databaseId -q '.[0].databaseId')\n" +
    "or in the Actions tab. Usually finishes in well under a minute."
);
