#!/usr/bin/env node
/**
 * Publish the static export in `out/` to the `gh-pages` branch.
 *
 * The site is built LOCALLY on purpose: `public/data/*.json` and
 * `public/collections/` are generated by `npm run data:*` using the Helius /
 * OpenSea keys in `.env.local`. Building here means those keys never need to
 * exist on GitHub — no Actions secrets, no CI credentials.
 *
 * `gh-pages` is force-pushed as a single orphan commit every time, so the
 * ~47 MB of generated data never accumulates across deploys.
 *
 *   npm run deploy      # build + publish
 */
import { execFileSync } from "node:child_process";
import { existsSync, rmSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const out = resolve(root, "out");

const run = (cmd, args, cwd) =>
  execFileSync(cmd, args, { cwd, stdio: "inherit" });

const capture = (cmd, args, cwd) =>
  execFileSync(cmd, args, { cwd, encoding: "utf8" }).trim();

// --- preflight -------------------------------------------------------------
if (!existsSync(out)) {
  console.error("out/ not found — run `npm run build` first.");
  process.exit(1);
}
for (const f of ["index.html", "CNAME"]) {
  if (!existsSync(resolve(out, f))) {
    console.error(`out/${f} is missing — refusing to deploy an incomplete build.`);
    process.exit(1);
  }
}

// Never publish a build that carries the offline pipeline or a credential.
const forbidden = ["scripts", "masks", ".env", ".env.local"];
for (const f of forbidden) {
  if (existsSync(resolve(out, f))) {
    console.error(`out/${f} exists — refusing to deploy. Investigate before retrying.`);
    process.exit(1);
  }
}

const remote = capture("git", ["remote", "get-url", "origin"], root);
console.log(`Deploying out/ -> gh-pages on ${remote}\n`);

// --- publish ---------------------------------------------------------------
// A throwaway repo inside out/, force-pushed. Keeps gh-pages at one commit.
rmSync(resolve(out, ".git"), { recursive: true, force: true });
run("git", ["init", "-q", "-b", "gh-pages"], out);
run("git", ["add", "-A"], out);
run("git", ["commit", "-q", "-m", `Deploy ${new Date().toISOString()}`], out);
run("git", ["push", "-q", "--force", remote, "gh-pages:gh-pages"], out);
rmSync(resolve(out, ".git"), { recursive: true, force: true });

console.log("\nDeployed. GitHub Pages will pick it up within a minute or two.");
